name: Deploy su Hostinger
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codice
      uses: actions/checkout@v3

    - name: Installa Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'npm'

    - name: Installazione dipendenze e Build
      run: |
        npm install
        npm run build

    - name: Carica il sito su Hostinger
      run: |
        sudo apt-get install -y lftp
        lftp -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" "${{ secrets.FTP_SERVER }}" -e "
          set ssl:verify-certificate no;
          set ftp:ssl-allow yes;
          mirror --reverse --verbose --no-perms --exclude DO_NOT_UPLOAD_HERE ./dist/ .;
          quit
        "
